spring:
  application:
    name: inventory
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOSTNAME}:8761/eureka

csv:
  data:
    path: ${CSV_FILE_PATH}