spring:
    application:
      name: registry

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_SERVICE_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/